// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamTest.proto

package cn.kungreat.netty.domain.grpc.stream;

public interface DataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.mail.stream.Data)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();
}
