// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamTest.proto

package cn.kungreat.netty.domain.grpc.stream;

public interface SendAgeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.mail.stream.SendAge)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
