// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mail.proto

package cn.kungreat.netty.domain.grpc;

public interface MailDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.mail.MailData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string address = 1;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>int32 phone = 2;</code>
   */
  int getPhone();
}
